# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buidkite-agent pipeline upload`

agents:
  queue: "mac"
env:
  IMAGE_ID: $IMAGE_ID
  SWIFTFORMAT_VERSION: $SWIFTFORMAT_VERSION

steps:
  #################
  # Lint Source files
  #################
  - group: "Linters"
    steps:
      - label: ":swift: SwiftLint"
        command: swiftlint
        notify:
          - github_commit_status:
              context: "SwiftLint"
        agents:
          queue: "linter"

      - label: ":swift: SwiftFormat Linting"
        plugins:
          - docker#v5.12.0:
              image: "ghcr.io/nicklockwood/swiftformat:$SWIFTFORMAT_VERSION"
              command: ["--lint", "Sources"]
              workdir: "${BUILDKITE_BUILD_CHECKOUT_PATH}"
          - docker#v5.12.0:
              image: "ghcr.io/nicklockwood/swiftformat:$SWIFTFORMAT_VERSION"
              command: ["--lint", "Tests"]
              workdir: "${BUILDKITE_BUILD_CHECKOUT_PATH}"
        agents:
          queue: "default"

      - label: ☢️ Danger - PR Check
        command: danger
        key: danger
        if: build.pull_request.id != null
        retry:
          manual:
            permit_on_passed: true
        agents:
          queue: linter

  #################
  # Build and Test
  #################
  - label: "📦 Build and Test Swift Package"
    key: "test"
    command: |
      validate_swift_package
    plugins: [$CI_TOOLKIT]

  ###################
  # Validate Podspec
  ###################
  - label: "🔬 Validate Podspecs"
    key: "validate"
    command: |
      .buildkite/commands/validate-pods.sh
    plugins: [$CI_TOOLKIT]

  #######################
  # Publish the Podspecs (if we're building a tag)
  #######################
  - label: "⬆️ Publish Podspecs"
    key: "publish"
    command: |
      .buildkite/commands/publish-pod.sh "Gravatar.podspec"
      .buildkite/commands/publish-pod.sh "GravatarUI.podspec"
    plugins: [$CI_TOOLKIT]
    depends_on:
      - "test"
      - "validate"
      - "lint"
    if: build.tag != null

  ###################
  # Prototype Builds of Demo Projects
  ###################
  - group: ":appcenter: Prototype Builds"
    steps:
      - label: "🛠️ Build Demo"
        key: build_demo
        depends_on: test
        plugins: [$CI_TOOLKIT]
        command: |
          install_gems
          BUILD_NUMBER=$BUILDKITE_BUILD_NUMBER make build-demo-for-distribution
        artifact_paths:
          - ".build/artifacts/*.ipa"
          - ".build/artifacts/*.dSYM.zip"

      - label: "⬆️ Upload Demo to App Center"
        depends_on: build_demo
        plugins: [$CI_TOOLKIT]
        command: .buildkite/commands/upload-to-appcenter.sh
        if: build.pull_request.id != null
