#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

export IMAGE_ID="xcode-16.2-macos-14.7.1-v1"

export CI_TOOLKIT="automattic/a8c-ci-toolkit#3.2.2"

export SWIFTFORMAT_VERSION=$( awk '/^--minversion/ { print $2 }' .swiftformat )

export DEMO_PROJECY="Demo/Gravatar-Demo.xcodeproj"